### PR TITLE
Make changelog only for current release

### PR DESCRIPTION
**Pull request by signedav**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Makes sense to me.
Should we add a link to https://github.com/opengisch/qfieldsync/releases where they can see images and older changelog entries too? The current visualization in the qgis plugin manager is kind of limited.

We could also add it as a todo for plugin_ci to generate that automatically on release.

**Comment by suricactus** [comment]
It is very common that users jumps to a new version skipping a few inbetween. Sometimes skipping even a few major releases, the average Joe hates updates. I think a link to https://github.com/opengisch/qfieldsync/releases is a must and can avoid a lot of headache for both sides.

**Comment by signedav** [comment]
image
Sadly html is not allowed in this section to create a link. So I hope this is sufficient.

**Comment by m-kuhn** [comment]
@signedav do you have an idea why the test is failing?

**Comment by signedav** [comment]
Checking right now. Weird that they did not failed when the DCIM synchronization has been integrated...

**Pull request merged**
