### PR TITLE
Move the core of the plugin into a separate library libqfieldsync

### PR DESCRIPTION
**Pull request by suricactus**
The motivation behind the split is in the need to use the existing QFieldSync plugin logic for other methods of export, including command line or other applicattions.

For end users the split should not affect them in any way.

For developers they should just remember to call `git submodule update`. But they already do, because `settingmanager` is also a submodule.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Very short merge window, I'd like to ask some questions here...

**Comment by suricactus** [comment]
Should I revert the change? Or we can comment here or on https://github.com/opengisch/qfieldsync/tree/qfield_cloud ?

**Comment by m-kuhn** [comment]
leave it like this for the moment.

1. main questions was if it makes sense to base qfieldcloud on qfieldsync
2. question was if we could use pypi instead of git submodule

**Comment by suricactus** [comment]
1) I think it is much safer to build on this. I am not aware of (any) big changes needed for the cloud export, otherwise we would duplicate the code. Or at least until we stop using `QgsOfflineEditing`. QFieldCloud would use only the new `libqfieldsync` subset, which can gradually move away from what is it now.

2) The `settingmanager` was already using a submodule, so I went for this. Also it is a bit easier to start development of the plugin - just `git clone && git submodule update`, rather than installing packages. No problem objections against hacing it as published package though, especially for the cloud.

**Comment by m-kuhn** [comment]
Regarding 1 I agree it's related to moving away from OE.
Regarding 2 I think it should be possible to deploy as python egg. Deploy to pypi using CI/CD has already been done for https://github.com/opengisch/pum

**Comment by suricactus** [comment]
It is not clear to me, should I make a pypi module now, or do it later?

**Comment by m-kuhn** [comment]
Can you talk to @3nids about the complexity of this? I think it would be very nice to have but it depends on how much time is required to set this up.

**Comment by 3nids** [comment]
it's pretty straightforward to push to PyPi.
Travis has dedicated deploy step. 
The effort is to produce the package, not tu push it.

**Pull request merged**
