### PR TITLE
Add explanations to the new project checker

### PR DESCRIPTION
**Pull request by suricactus**
image

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1805 Add explanations about the new project checker feedback in QFieldSync](https://app.clickup.com/t/2192114/QF-1805)

**Review by nirvn — APPROVED** [review]

**Comment by nirvn** [comment]
@suricactus , it'd eventually be good to move this stuff onto the QGIS class that does checks (currently used in the layout designer). TODO >= 4.1 :smiley:

**Comment by suricactus** [comment]
@nirvn what is this class?

**Comment by nirvn** [comment]
@suricactus , looking for the class name now :)

**Comment by nirvn** [comment]
@suricactus , QgsAbstractValidityCheck

The layout implementation looks like this:
image

**Comment by suricactus** [comment]
Thanks <3

**Pull request merged**
