### PR TITLE
Photo_path fixes

### PR DESCRIPTION
**Pull request by signedav**
- Check if layer is vector layer on attachment fields
- use row as index

Before I received this:
```
2020-03-02T14:48:25     WARNING    Traceback (most recent call last):
              File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py", line 94, in 
              self.infoLabel.linkActivated.connect(lambda: self.show_settings())
              File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/package_dialog.py", line 153, in show_settings
              dlg = ProjectConfigurationDialog(self.iface, self.iface.mainWindow())
              File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/project_configuration_dialog.py", line 79, in __init__
              self.reloadProject()
              File "/home/david/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/gui/project_configuration_dialog.py", line 120, in reloadProject
              for field in layer.fields():
             AttributeError: 'QgsRasterLayer' object has no attribute 'fields'
```
And I got empty fields...

### CODE REVIEW

**Comment by signedav** [comment]
@3nids Additionally to these fixes I would like to discuss these things:
- As far as I understand that on apply it adds the custom properties to the original project. The offline project never gets them. Is something missing?
- I'm not sure if you have been in this discussion on a weekly teammeeting. We talked about the sub-path, that this should be defined as well. Means it would be nice to have as a default value `DCIM/` included.
- Should the extension (.jpg) be added by QField? If so we would need to make a note somewhere in the GUI.

**Comment by 3nids** [comment]
Thanks for the fix!

> As far as I understand that on apply it adds the custom properties to the original project. The offline project never gets them. Is something missing?

It might be an issue in offline editing. I will have a look.

> I'm not sure if you have been in this discussion on a weekly teammeeting. We talked about the sub-path, that this should be defined as well. Means it would be nice to have as a default value DCIM/ included.

Is this what you mean https://github.com/opengisch/qfieldsync/pull/137 ?

> Should the extension (.jpg) be added by QField? If so we would need to make a note somewhere in the GUI.

I would say that we test if `\.jpe?g/i` is the exstension and we append if not. Works for you?

**Comment by signedav** [comment]
> I would say that we test if \.jpe?g/i is the exstension and we append if not. Works for you?

Okaydokey.

**Comment by m-kuhn** [comment]
No risk that someone uses .png, .raw., .JPEG, ...?

**Comment by 3nids** [comment]
> .png, .raw.

well, if then, jpg is going to be appended

>  .JPEG

this is handled by the nice regex ;)

**Comment by signedav** [comment]
As far as I understand our existing code, the photos taken by the camera are stored as a `.jpg`.

**Comment by m-kuhn** [comment]
> > .png, .raw.
> 
> well, if then, jpg is going to be appended
> 

which would render the file useless, which is my concern



> As far as I understand our existing code, the photos taken by the camera are stored as a `.jpg`.

Native one also? If that's forced anyway, no further questions.

**Comment by signedav** [comment]
I see three possibilities:
- we have no extension in our default expression - means we make the user to not define an expression -> and then we add jpg like it's done currently.
- we parse the file for an extension. Whatever it is, we put the camera result in there. Leaf it to the user, if he tries to store it wherever. \*
- we parse for jpg / jpeg like @3nids suggested...

 \* this could maybe be reused for upcoming attachments with other file types.

**Comment by 3nids** [comment]
> which would render the file useless, which is my concern

why? are there some system camera which produces other files than JPG?
if so, we could take the other approach: strip away any extension from the expression and append the extension from the system file name?

**Comment by signedav** [comment]
WhatsApp Image 2020-03-04 at 10 03 41
Open Camera App

So I suggest:
- QFieldSync has the default expression without any extension (maybe tool tip)
- Remove extension
- If I can get the type from the camera, I use it
- Otherwise append ".jpg"

Fine?

**Comment by 3nids** [comment]
perfect to me

**Comment by signedav** [comment]
I committed the light version with replacing any extension with`.jpg`

Why I did not detect the type returned by the camera? Because the camera does not return any type, not even a file name. Currently it's solved by passing the camera the filename (and path) where to store the image. This means currently only JPGs are supported.

**Pull request merged**
