### PR TITLE
UI improvements following cloud testing

### PR DESCRIPTION
**Pull request by nirvn**
@suricactus , a couple of UI improvements.

First, the main window qfieldsync toolbar now uses QFieldCloud's main blue identity:
image

IMHO makes it pop out a lot more, esp. on dark theme.

Second, the projects overview dialog has gotten a bit of love. Improvements include
- a proper synchronization icon (the generic cloud didn't convey what the action was really)
- to link with QField, I've used the 'delete red' for the delete icon
- the black icons now all have a tiny semi-transparent white buffer to make those pop out a bit more on dark themes

image

I've cleaned up the browser tree actions (better icons, harmonized capitalization):
image
 _Note how much nicer the blue cloud looks here_

Finally, I've modified the string for some main toolbar / menu actions. The QFieldCloud name now appears (always good to remember the users which cool product he/she is using ;)) and tried to make it easier to distinguish current qfieldcloud project properties vs. current project configuration. The latter properly still needs more thinking but it's already better.
image

Prologue: more love for the QFieldCloud login dialog:
image

Improvements include:
- A string to pitch QFieldCloud to new users and an hyperlink for hi/she/they to learn more
- The server combo box is hidden by default and reveal upon double-clicking the logo image (just like QField app)
- The form UI has been cleaned up a bit, and the dialog uses a standard buttons box widget to better blend in with users' OSes.

### CODE REVIEW

**Comment by nirvn** [comment]
Last improvement, harmonize qfieldsync's QFieldCloud login popup with that of QField to increase coherence:
image

**Comment by nirvn** [comment]
@signedav , I didn't have the time / energy to implement a double click on the QFieldCloud logo to show/hide the server combobox, that'd be worth doing.

Also, it'd be worth adding a QLabel with an hyperlink to qfield.cloud website in the login screen (the same way we do in the QField app). If someone ventures into clicking on the cloud button on his/her toolbar, that hyperlink would help reach more information and account registration.

**Comment by nirvn** [comment]
@signedav , done.

**Comment by nirvn** [comment]
I just realized I've used @signedav 's nickname when I meant to ping @suricactus :open_mouth: --

**Review by suricactus — APPROVED** [review]
Lovely improvements. Very big thanks!

**Pull request merged**
