### PR TITLE
Fix the icons without changing the current workdir globally

### PR DESCRIPTION
**Pull request by suricactus**
The old solution cause the whole python environment in QGIS to change.
This will break so many scripts!  Fixes the fix in #327

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Looks good

**Comment by m-kuhn** [comment]
Use this construct for extra karma points

```
class CustomCwd(object):
    def __init__(self, cwd):
        self.old_cwd = os.getcwd()
        os.chdir(cwd)
  
    def __exit__(self):
        os.chdir(self.old_cwd)


with CustomCwd(str(Path(....))):
    self.loadUi()
```

**Comment by suricactus** [comment]
Or even better - a decorator :)

**Comment by m-kuhn** [comment]
Decorate the constructor? Or something else? Whatever works for you :-)

**Pull request merged**
